//HintName: My.Namespace.PersonMapFromDataRecordExtension.g.cs
// <auto-generated>
using System.Data;

namespace My.Namespace;
public static class __PersonExtension__
{
    static class ordinal
    {
        public static bool __initialized__;
        public static int Id;
        public static int Age;
        public static int Name;
        public static int MiddleName;
    }
    public static Person ToPerson(this IDataRecord record)
    {
        if (!ordinal.__initialized__)
        {
            ordinal.Id = record.GetOrdinal(nameof(Person.Id));
            ordinal.Age = record.GetOrdinal(nameof(Person.Age));
            ordinal.Name = record.GetOrdinal(nameof(Person.Name));
            ordinal.MiddleName = record.GetOrdinal(nameof(Person.MiddleName));
            System.Threading.Thread.MemoryBarrier();
            ordinal.__initialized__ = true;
        }
        return new Person
        {
            Id = record.GetInt32(ordinal.Id),
            Age = record.IsDBNull(ordinal.Age) ? null : record.GetInt32(ordinal.Age),
            Name = record.GetString(ordinal.Name),
            MiddleName = record.GetString(ordinal.MiddleName),
        };
    }
}
