name: Build, Test and Publish

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
        include-prerelease: true
    - name: build
      run: dotnet build --configuration Release
    - name: test
      run: dotnet test --no-build --configuration Release Net.Code.ADONet.Tests.Unit
    - name: pack
      run: dotnet pack Net.Code.ADONet -o out
    - name: push to nuget
      run: dotnet push out\Net.Code.ADONet.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
    - name: push symbols to nuget
      run: dotnet push out\Net.Code.ADONet.*.snupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
